name: lasheen_qr

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  path: ^1.9.0
  file_selector: ^1.0.3
  zxing2: ^0.2.3
  image: ^4.2.0
  handy_window: ^0.4.0
  adwaita: ^1.1.0
  pretty_qr_code: ^3.3.0
  url_launcher: ^6.3.0
  yaru_widgets: ^3.6.0
  flutter_spinbox: ^0.13.1
  screenshot: ^3.0.0
  package_info_plus: ^8.0.2 
  screenshotx: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/madebylasheen.png
    - assets/icon.png