name: qr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  r_scan: ^0.1.6+1
  camera: ^0.10.0+4
  path_provider: ^2.0.11
  path: ^1.8.2
  qr_code_vision: ^0.1.0
  qr_utils: ^0.1.5
  file_selector: ^0.9.2+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true