name: lasheen_qr

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4
  path_provider: ^2.0.11
  path: ^1.8.2
  file_selector: ^0.9.2+2
  zxing2: ^0.1.1
  image: ^3.2.2
  image_picker: ^0.8.6
  handy_window: ^0.1.9
  adwaita: ^0.5.2
  window_manager: ^0.2.8
  pretty_qr_code: ^2.0.2
  url_launcher: ^6.1.7
  yaru_widgets: ^2.0.0-beta-2
  flutter_spinbox: ^0.11.0
  screenshot: ^1.2.3
  gallery_saver: ^2.3.2
  android_path_provider: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true