name: Build Flatpak

on:
  workflow_dispatch:

env:
  project-id: codes.merritt.FeelingFinder

jobs:
  build-flutter-app:
    name: Build and compressed Flutter app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      
      
      - name: Compress Flutter build
        run: tar -C build/linux/x64/release/bundle -cvf FlutterApp-Linux-Portable.tar.gz .


      - name: Upload app archive for next steps
        uses: actions/upload-artifact@v3
        with:
          path: FlutterApp-Linux-Portable.tar.gz

  build-flatpak:
    name: Build flatpak
    needs: build-flutter-app
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download app archive
        uses: actions/download-artifact@v3

      - name: Build .flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: FlutterApp.flatpak
          manifest-path: flathub/dev.lasheen.qr.json

      - name: Upload .flatpak artifact to workflow
        uses: actions/upload-artifact@v3
        with:
          name: Flatpak artifact
          path: FlutterApp.flatpak
