name: "Build"

on:
  workflow_dispatch:

jobs:  
  build:      
    name: Build & Release 
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: '3.24.3'

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Install linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev


      - name: Build Linux App
        run: |
          # flutter build linux --release --target-platform=linux-arm64
          flutter build linux --release --target-platform=linux-x64

      - name: Archive Linux App
        run: |
          tar -czvf build/linux_build_x64.tar.gz build/linux/x64/release/bundle/qr

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: build/linux_build_x64.tar.gz
